spring.application.name=certificategeneration

spring.datasource.url=jdbc:postgresql://localhost:5432/digital

spring.datasource.username=
spring.datasource.password=
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA Configuration

spring.jpa.hibernate.ddl-auto=create
logging.level.com.dsjobby.crm=DEBUG

spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Server Configuration
server.port=8081